### ISSUE TITLE
not enough arguments in call to Auth.GetCurrentUser

### ISSUE THREAD

**Issue by batuhan** [qor/qor-example#101]
I'm getting this error `not enough arguments in call to Auth.GetCurrentUser` when I try to `go run main.go`

<img width="458" alt="screen shot 2017-08-02 at 11 27 57" src="https://user-images.githubusercontent.com/535988/28864606-c07904be-7775-11e7-830b-33e18b548634.png">

I'm not very experienced with Go or QOR so I'm not sure how to fix this. I think something changed with the `auth` package but I'm not sure.

When I change the line to `	currentUser, _ := Auth.GetCurrentUser(c.Writer, c.Request).(qor.CurrentUser)` another part of the app just breaks and requires changes.

Any ideas on how to fix this?

**Comment by batuhan** [comment]
I've rolled back to https://github.com/qor/qor-example/tree/2295ce236af71de6c33175af564ca1c5ab112410

**Comment by jinzhu** [comment]
It is not necessary to pass `writer` to the getcurrentuser method already.
