### ISSUE TITLE
Authentication error - invalid account

### ISSUE THREAD

**Issue by ftomza** [qor/qor-example#102]
Hi!

When logging in through the authentication form with the standard login dev@getqor.com, an **"invalid account"** message is displayed.
A clean version of **qor-example** is installed and the default data is loaded.
After studying it was found out that the form of authentication looks in the table **"auth_identities"**, which at the moment is empty.
How to fix the situation?

```
(/Users/artzab/develop/GoLang/VIARFOLLY/src/github.com/qor/auth/providers/password/handlers.go:27) 
[2017-08-09 10:47:40]  [0.73ms]  SELECT * FROM `auth_identities`  WHERE `auth_identities`.`deleted_at` IS NULL AND ((`auth_identities`.`provider` = 'password') AND (`auth_identities`.`ui_d` = 'dev@getqor.com'))  
[0 rows affected or returned ] 
```

**Comment by jinzhu** [comment]
Hi @ftomza 

Sorry, we haven't migrate db seeds after integrate new `Auth`, so there is no user could be logged by default, you need to register a new user by default, and use them to login...

**Comment by ftomza** [comment]
Well, how to register it, is there an example?

**Comment by jinzhu** [comment]
Just do it in the UI.

@ftomza maybe you could follow github.com/qor/auth's README, it is not finished yet, if anything not clear, open an issue there.
