### ISSUE TITLE
Error when pulling dependencies

### ISSUE THREAD

**Issue by dmbr0** [qor/qor-example#104]
I am getting the following error when pulling dependencies from the example project folder

`go get -u ./...`

`# github.com/qor/qor-example/db/seeds`
`runtime.main_main·f: relocation target main.main not defined`
`runtime.main_main·f: undefined: "main.main"`

**Comment by jinzhu** [comment]
seems like not a qor related question, maybe use `$GOPATH/src/github.com/qor/qor/update_all_qor_repos.sh` to update all qor libs first?
