### ISSUE TITLE
Blank page when accessing /admin

### ISSUE THREAD

**Issue by dmbr0** [qor/qor-example#105]
`$ go run main.go`
`Failed to find configuration config/application.yml`
`Failed to find configuration config/smtp.yml, using example file config/smtp.example.yml`
`Failed to find configuration config/database.yml, using example file config/database.example.yml`
`Failed to create unique index for translations key & locale, got: Error 1170: BLOB/TEXT column 'key'`
 `used in key specification without a key length`

`(Error 1170: BLOB/TEXT column 'key' used in key specification without a key length)` 
`[2017-08-26 18:30:21]  `
`[warning] duplicated callback `qor_admin:composite_primary_key` from` `/Users/alexander/go/src/github.com/qor/admin/composite_primary_key_callback.go:31`
`[warning] duplicated callback `qor_admin:composite_primary_key` from` `/Users/alexander/go/src/github.com/qor/admin/composite_primary_key_callback.go:32`
`[warning] duplicated callback `qor_admin:composite_primary_key` from` `/Users/alexander/go/src/github.com/qor/admin/composite_primary_key_callback.go:32`
`Listening on: 7000`
`2017/08/26 18:31:27 Finish [GET] /admin Took 0.02ms`
`failed to find template: auth/login`
`failed to find template: auth/login`

**Comment by jinzhu** [comment]
Are you using the latest auth? maybe try to get latest qor libs with `$GOPATH/src/github.com/qor/qor/update_all_qor_repos.sh`?
