### ISSUE TITLE
Fail to save association when we update a record

### ISSUE THREAD

**Issue by shenzhaoyan** [qor/qor-example#110]
Please check `fail-to-save-association` branch.

You can test it like this:
1. Create two sports first.
2. Open the product edit page, choose a sport, then save the product, it works.
3. Open the product edit page (the same product), but not edit it, then save the product, it will fail, the error messages are: `Title can't be blank`, `TitleWithSlug can't be blank`
4. Open the product edit page (the same product), choose another sport, then save the product, it works.

**Comment by Jeweller-Tsai** [comment]
@binku87 could please investigate this one? Thank you

**Comment by shenzhaoyan** [comment]
Thanks @binku87 .

Fixed by adding `db.Model(&product).Related(&product.Sport, "Sport")` to product validate func.
