### ISSUE TITLE
function error in run go main.go

### ISSUE THREAD

**Issue by monlone** [qor/qor-example#113]
i just execute "go run main.go", i get this error flow:

github.com/qor/auth
../../../../../src/github.com/qor/auth/session_storer.go:56: too many arguments in call to sessionStorer.SessionManager.Add
	have (http.ResponseWriter, *http.Request, string, string)
	want (*http.Request, string, interface {})
../../../../../src/github.com/qor/auth/session_storer.go:61: too many arguments in call to sessionStorer.SessionManager.Pop
	have (http.ResponseWriter, *http.Request, string)
	want (*http.Request, string)
../../../../../src/github.com/qor/auth/session_storer.go:67: too many arguments in call to sessionStorer.SessionManager.Flash
	have (http.ResponseWriter, *http.Request, session.Message)
	want (*http.Request, session.Message)
../../../../../src/github.com/qor/auth/session_storer.go:72: too many arguments in call to sessionStorer.SessionManager.Flashes
	have (http.ResponseWriter, *http.Request)
	want (*http.Request)

how can i to fix it?thank you!

**Comment by jinzhu** [comment]
@monlone Update all your qor libs with `$GOPATH/src/github.com/qor/qor/update_all_qor_repos.sh`
