### ISSUE TITLE
failed to find template: auth/login

### ISSUE THREAD

**Issue by alphaXkiller** [qor/qor-example#115]
Fresh install qor-example, running on go version: 1.9.1
when I goto auth/login page, error appears? Any advice?

Thank you

**Comment by jinzhu** [comment]
Make sure all qor libs are updated and try again?

`$GOPATH/src/github.com/qor/qor/update_all_qor_repos.sh`

**Comment by alphaXkiller** [comment]
@jinzhu that works. Thank you
