### ISSUE TITLE
Lots of issues with this latest merge folks

### ISSUE THREAD

**Issue by randomtask2000** [qor/qor-example#125]
`db` module has moved to config causing `seeds` to fail.  `admin` has been removed but is included by `seeds` and now fails. I'm surprised we don't have unit tests to test all these includes before we merge to `master`.  

Any feedback is appreciated!

**Comment by notdang** [comment]
@randomtask2000  check this: https://github.com/qor/qor-example/pull/126

**Comment by jinzhu** [comment]
Sorry for that, should been fixed.

**Comment by randomtask2000** [comment]
Cool, I'll have a look!
