### ISSUE TITLE
qor-example demo is broken due to moved packages

### ISSUE THREAD

**Issue by koreset** [qor/qor-example#128]
Hello
I was trying to run the example app and populate the data when I kept running into a missing package 	error for "github.com/qor/qor-example/config/admin"
I realised from the source that the admin package no longer exists under config. Does this mean that we point the import to the app/admin package?

**Comment by randomtask2000** [comment]
Plus the seeder is broken :( You may want to try #126 from @notdang - I think he fixed it.

**Comment by randomtask2000** [comment]
It's too bad that there isn't enough test coverage built in to prevent these type of merges.

**Comment by jinzhu** [comment]
@randomtask2000 sorry for this, we have already fixed that.
