### ISSUE TITLE
cannot find package "enterprise.getqor.com/promotion"

### ISSUE THREAD

**Issue by magicool** [qor/qor-example#130]
can't load package: package enterprise.getqor.com/promotion

**Comment by cryptix** [comment]
I also find these references to close packages confusing.

If you make an example project please include all the code and don't tease about half finished features.

**Comment by jinzhu** [comment]
Hi @magicool 

How do you get this errors? I think run `go run main.go` won't call any code from ` enterprise.getqor.com/promotion`?

**Comment by arnaud-web** [comment]
Hi,

Yes it does. 

Just by running `go run main.go ` we have this error: 


```
app/enterprise/promotion.go:7:2: cannot find package "enterprise.getqor.com/promotion" in any of:
        /usr/local/go/src/enterprise.getqor.com/promotion (from $GOROOT)
        /Users/arnaud/go/src/enterprise.getqor.com/promotion (from $GOPATH)
```

**Comment by shahidkhans** [comment]
while running the command : go get -u github.com/qor/qor-example is giving the below error.
C:\Users\Sid>go get -u github.com/qor/qor-example
# cd .; git clone https://github.com/theplant/qor-promotion C:\Users\Sid\go\src\enterprise.getqor.com\promotion
Cloning into 'C:\Users\Sid\go\src\enterprise.getqor.com\promotion'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package enterprise.getqor.com/promotion: exit status 128

**Comment by qbig** [comment]
same issue here. I think it's because of this .
```golang

/Users/qiaoliang/go/src/github.com/qor/qor-example/app/enterprise/promotion.go:
    5  	"fmt"
    6  
    7: 	"enterprise.getqor.com/promotion"
    8  	"github.com/qor/admin"
    9  	"github.com/qor/qor"
```

**Comment by jinzhu** [comment]
Hi @all 

Sorry for the issue, already fixed that.
