### ISSUE TITLE
why cannot signin with the demo account

### ISSUE THREAD

**Issue by 417806161** [qor/qor-example#147]
``<b>Demo Account: dev@getqor.com / testing</b>
i sign in with this account,but doesnot work
so i check the users table ,i can't found this account
how can i sign in with this account
and i sign up a new account,it will success
but i can't signin this new account
i hope somebody give me a tips
think you

**Comment by thanateros** [comment]
Sounds like you didn't load the sample data: https://github.com/qor/qor-example#generate-sample-data

**Comment by 417806161** [comment]
yeap,i fix it yesterday,i forgot run the Generate sample data command ,thanks

**Comment by thanateros** [comment]
Excellent! go ahead and close this issue when you get time so no-one thinks this is still an open issue.  And happy coding.

**Comment by 417806161** [comment]
yeah，thanks
