### ISSUE TITLE
Loading in seed data

### ISSUE THREAD

**Issue by wiziah** [qor/qor-example#15]
When I run main.go to load in the seed data I get the following error:

←[35m(z:/goworkspace/src/github.com/qor/qor-example/db/seeds/main.go:286)←[0m
←[33m[2015-10-15 20:41:13]←[0m  ←[36;1m[0.00ms]←[0m  SELECT  \* FROM `size_variations`  WHERE (`size_variations`.deleted_at IS NULL OR `size_variations`.deleted_at <= '0001-01-02')

←[35m(z:/goworkspace/src/github.com/qor/qor-example/db/seeds/main.go:312)←[0m
←[33m[2015-10-15 20:41:13]←[0m  ←[36;1m[3.04ms]←[0m  INSERT INTO `orders` (`shipping_address_id`,`billing_address_id`,`payment_amount`,`abandoned_reason`,`user_id`,`state`,`created_at`,`updated_at`,`d
eleted_at`,`discount_value`) VALUES ('1','1','0','','1','draft','2015-10-15T20:41:13+11:00','2015-10-15T20:41:13+11:00','<nil>','0')
panic: runtime error: integer divide by zero
[signal 0xc0000094 code=0x0 addr=0x0 pc=0x406416]

goroutine 1 [running]:
main.createOrders()
        z:/goworkspace/src/github.com/qor/qor-example/db/seeds/main.go:316 +0x9e6
main.createRecords()
        z:/goworkspace/src/github.com/qor/qor-example/db/seeds/main.go:74 +0x93c
main.main()
        z:/goworkspace/src/github.com/qor/qor-example/db/seeds/main.go:47 +0x4e

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0xc0821695e0)
        c:/go/src/database/sql/sql.go:634 +0x4c
created by database/sql.Open
        c:/go/src/database/sql/sql.go:481 +0x33d
exit status 2
## 

I can access the site on port 7000..there isn't any sample data loaded in..
Your assistance would be much appreciated.

**Comment by jinzhu** [comment]
should been fixed, thank you for your report
