### ISSUE TITLE
qor-example amazon pay config bug

### ISSUE THREAD

**Issue by swrdfish** [qor/qor-example#156]
while trying to run the example app the following error occurs: 
`# github.com/qor/qor-example/config
config/config.go:94:12: cannot use amazonpay.New(&amazonpay.Config literal) (type amazonpay.AmazonPayService) as type *amazonpay.AmazonPay in assignment: need type assertion`

**Comment by shijianzhong** [comment]
hi，How can I solve this problem?

**Comment by vladim1234** [comment]
+1

**Comment by shijianzhong** [comment]
AmazonPay      *amazonpay.AmazonPay
	AmazonPay      amazonpay.AmazonPayService

**Comment by shijianzhong** [comment]
@vladim1234

**Comment by vladim1234** [comment]
Thanks!
