### ISSUE TITLE
Missing functions on i18n.I18n

### ISSUE THREAD

**Issue by beaspider** [qor/qor-example#16]
Looks like this [commit](https://github.com/qor/qor-example/blob/c332ffe42ebfb993e7b42aa0d207410ef8fe847e/config/funcMap.go) is using a different version/branch of `github.com/qor/qor/i18n`?

github.com/qor/qor-example/config/funcMap.go:14: Config.I18n.EnableInlineEdit undefined (type *i18n.I18n has no field or method EnableInlineEdit)
github.com/qor/qor-example/config/funcMap.go:18: undefined: i18n.RenderInlineEditAssets

**Comment by jinzhu** [comment]
should been fixed, thank you for your report
