### ISSUE TITLE
qorJob.AddTableRow undefined

### ISSUE THREAD

**Issue by skpark1987** [qor/qor-example#24]
I just run "go run db/seeds/main.go" command, and following bug appear.
config/admin/worker.go:90: qorJob.AddTableRow undefined (type worker.QorJobInterface has no field or method AddTableRow)
config/admin/worker.go:93: qorJob.AddTableRow undefined (type worker.QorJobInterface has no field or method AddTableRow)

**Comment by jinzhu** [comment]
Hi @skpark1987 

We just changed the API a little bit, haven't push change made in qor-example to master, just pushed the change.

Thank you for your report.
