### ISSUE TITLE
function "t" not defined

### ISSUE THREAD

**Issue by guycalledseven** [qor/qor-example#26]
Hi

Commit "inline-edit: add translations for home page" (84953118a612903d6081a4a5c2721926ea6e743e) broke qor-example.

go version go1.6.2 linux/amd64, products pages show blank with following error:

```
Got error when render template product_show: template: application.tmpl:25: function "t" not defined
[GIN] 2016/04/25 - 11:31:55 | 200 |    8.014256ms | 10.211.55.2 |   GET     /products/blue-qor-watch_blue-light
```

products controller passes own funcMap to render.Render which does not have t defined.
home controller has  "t"  defined in i i18n funcs:

```
	i18nFuncMap := inline_edit.GenerateFuncMaps(i18n.I18n, "en-US", nil)
	config.View.Funcs(i18nFuncMap).Execute...
```

**Comment by jinzhu** [comment]
Hi @guycalledseven 

Sorry for the problem, should been fixed.
