### ISSUE TITLE
After installed qor-example product section not working in the admin backend

### ISSUE THREAD

**Issue by rahu431** [qor/qor-example#28]
←[35m(Error 1146: Table 'qor_example.products' doesn't exist)←[0m
←[33m[2016-05-05 13:34:58]←[0m ←[31;1m ←[0m
[WARNING] Qor SEO: The parameter you passed is not a Struct

←[35m(Error 1146: Table 'qor_example.products' doesn't exist)←[0m
←[33m[2016-05-05 13:34:58]←[0m ←[31;1m ←[0m
[GIN] 2016/05/05 - 13:34:58 |←[97;42m 200 ←[0m|        62.5ms | ::1 |←[97;44m  ←
[0m GET     /
When i run main.go it shows these below errors
←[35m(Error 1146: Table 'qor_example.products' doesn't exist)←[0m
←[33m[2016-05-05 13:34:58]←[0m ←[31;1m ←[0m
[WARNING] Qor SEO: The parameter you passed is not a Struct
[GIN] 2016/05/05 - 13:34:58 |←[97;42m 200 ←[0m|     62.4987ms | ::1 |←[97;44m  ←
[0m GET     /

←[35m(Error 1146: Table 'qor_example.products' doesn't exist)←[0m
←[33m[2016-05-05 13:34:58]←[0m ←[31;1m ←[0m
Finish [GET] /admin/widgets/inline-edit Took 31.24ms

**Comment by jinzhu** [comment]
should been fixed, thank you for your report
