### ISSUE TITLE
qor example doesn't build :: collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by bitcubate** [qor/qor-example#31]
Hi, I am facing an issue where I can't build the qor example. Can you guide me?

Errors:

[root@jesusrico TA]# export GOPATH=/media/matrix/TA/
[root@jesusrico TA]# go get -u github.com/qor/qor-example
#github.com/fatih/color
src/github.com/fatih/color/color.go:9:31: error: import file ‘github.com/mattn/go-colorable’ not found
  "github.com/mattn/go-colorable"
                               ^
src/github.com/fatih/color/color.go:10:28: error: import file ‘github.com/mattn/go-isatty’ not found
  "github.com/mattn/go-isatty"
                            ^
src/github.com/fatih/color/color.go:17:16: error: reference to undefined name ‘isatty’
 var NoColor = !isatty.IsTerminal(os.Stdout.Fd())
                ^
src/github.com/fatih/color/color.go:150:14: error: reference to undefined name ‘colorable’
 var Output = colorable.NewColorableStdout()
              ^
[root@jesusrico TA]# go get -u github.com/mattn/go-colorable
[root@jesusrico TA]# go get -u github.com/mattn/go-isatty
[root@jesusrico TA]# go get -u github.com/qor/qor-example
#github.com/qor/qor-example
/media/matrix/TA/pkg/gccgo_linux_amd64/github.com/fatih/libcolor.a(_go_.o): In function `github_com_fatih_color..import':
/media/matrix/TA/src/github.com/fatih/color/color.go:17: undefined reference to `github_com_mattn_go_isatty.IsTerminal'
/media/matrix/TA/src/github.com/fatih/color/color.go:150: undefined reference to `github_com_mattn_go_colorable.NewColorableStdout'
collect2: error: ld returned 1 exit status

[root@jesusrico TA]# go version
go version go1.6.1 gccgo (GCC) 6.1.1 20160501 linux/amd64

**Comment by jinzhu** [comment]
`go get -u -f ./...`
