### ISSUE TITLE
Generate sample data -> sample image download error 

### ISSUE THREAD

**Issue by caghan** [qor/qor-example#32]
Error at  `$ go run db/seeds/main.go` :

> open file ("http://qor3.s3.amazonaws.com/01-tee-c.20160316044516567824937.png") failure, got err open /home/caghan/Development/go-work/src/github.com/qor/qor-example/tmp/01-tee-c.20160316044516567824937.png: no such file or directory

It is because the folder **tmp** doesn't exist in the repo tree. So you may fix it by adding tmp folder to root of example.

`mkdir $GOPATH/src/github.com/qor/qor-example/tmp`

P.S. BTW qor seems promising! :100:

**Comment by jinzhu** [comment]
Thank you for your report, just fixed that.
