### ISSUE TITLE
edit fields by roles

### ISSUE THREAD

**Issue by oonxt** [qor/qor-example#36]
How do I edit different fields with different roles?
for example
role admin:
  EditAttrs("role"....)

role user:
  EditAttrs("password", "email" .....)

role manager:
  EditAttrs("point"...)

**Comment by jinzhu** [comment]
You could set permission by metas, for example:

```go
user.Meta(&admin.Meta{Name: "Email", permission: roles.Allow(roles.Update, "admin, "user").Deny(roles.Update, "manager)
```

**Comment by oonxt** [comment]
yes. thx.
