### ISSUE TITLE
LayoutPath and LayoutFuncMaker not found

### ISSUE THREAD

**Issue by tasdingoo** [qor/qor-example#37]
File config/auth/auth.go line 36 37 

May be the [authboss](http://gopkg.in/authboss.v0) I used is the newest?????

**Comment by wimigame** [comment]
同问

**Comment by nateweisiger** [comment]
This happens because the newest version on authboss no longer has these properties.

I solved this by saving the version that ships with the example into my vendors folder.

**Comment by jinzhu** [comment]
We already bundled authboss into qor example, so if you are using golang v1.6+, it should works.
