### ISSUE TITLE
ERROR run

### ISSUE THREAD

**Issue by grengojbo** [qor/qor-example#45]
[auth]     Route: /auth/logout

Duplicated meta Name defined for resource Widget Content
goroutine 1 [running]:
runtime/debug.Stack(0x2d, 0xc420a89770, 0x2)
    /usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
    /usr/local/opt/go/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/qor/qor/utils.ExitWithMsg(0x674880, 0xc420e54c90, 0xc420a89770, 0x2, 0x2)
    /Users/jbo/go/src/github.com/qor/qor/utils/utils.go:152 +0x161
github.com/qor/admin.(_Resource).Meta(0xc4209d5040, 0xc420109d40, 0xc420a89820)
    /Users/jbo/go/src/github.com/qor/admin/resource.go:45 +0x2f1
github.com/qor/widget.(_QorWidgetSetting).ConfigureQorResource(0xc4208c4a80, 0xa72e80, 0xc4209d5040)
    /Users/jbo/go/src/github.com/qor/widget/setting.go:131 +0x13e
github.com/qor/admin.(_Resource).configure(0xc4209d5040)
    /Users/jbo/go/src/github.com/qor/admin/resource.go:497 +0x21b
github.com/qor/admin.(_Admin).MountTo(0xc420170000, 0x756fbd, 0x6, 0xc420ad7290)
    /Users/jbo/go/src/github.com/qor/admin/route.go:268 +0x262
main.main()
    /Users/jbo/go/src/github.com/qor/qor-example/main.go:20 +0xc3
Listening on: 7000

**Comment by jinzhu** [comment]
should been fixed, thank you for your report
