### ISSUE TITLE
能否兼容到go 1.7.1？

### ISSUE THREAD

**Issue by leenux** [qor/qor-example#48]
在1.7.1下单元测试 发现metadata包需要改为cloud.google.com/go/compute/metadata

**Comment by binku87** [comment]
Hi

能给多点具体信息吗？跑什么才会出现你说的问题？

**Comment by leenux** [comment]
执行单元测试go test -v ./...
首先出现编译错误，提示信息是需要把包改为cloud.google.com/go/compute/metadata

**Comment by binku87** [comment]
请问是在你自己的项目上执行go test -v ./...吗？qor-example本身没有单元测试。

qor-exmaple本身没有用metadata, 不过用到的oauth2用到了metadata.

![image](https://cloud.githubusercontent.com/assets/147775/19507597/a1ced062-9606-11e6-80e0-618cb29ea92a.png)

**Comment by binku87** [comment]
这样跑会把vendor里面的都跑一边，你可以通过这个跑`go test $(go list ./... | grep -v /vendor/ | grep  -v /db/)`

**Comment by Gaubee** [comment]
确实在1.7+上面跑不过。
版本：`go1.7.3 windows/amd64`
运行报错：
```
# github.com/qor/admin                                       
..\admin\meta.go:49: undefined: resource.MetaConfigInterface 
```
