### ISSUE TITLE
Workers Select not works

### ISSUE THREAD

**Issue by grengojbo** [qor/qor-example#49]
Demo app [Workers](http://demo.getqor.com/admin/workers)  click **+** (button)
 Add Worker -> click **Export Translations** or other admin.SelectOneConfig...

Is not display list items
![workers_select_error](https://cloud.githubusercontent.com/assets/144388/19761438/a3766716-9c3e-11e6-8c8f-1a83e776560f.png)

**Comment by jinzhu** [comment]
should been fixed, thank you for your report
