### ISSUE TITLE
No configurable settings for this container

### ISSUE THREAD

**Issue by majidkarimizadeh** [qor/qor-example#58]
hi...
my widget edit get me this statment...

![screenshot from 2017-01-30 12-21-19](https://cloud.githubusercontent.com/assets/20487980/22416930/a6172c42-e6e6-11e6-8a78-c01344b28ffc.png)

can any one help me what should i have done?

**Comment by jinzhu** [comment]
just means this widget has no configurable setting, it is fine.

**Comment by majidkarimizadeh** [comment]
But it is fine on my localhost...but in server i just get this error

**Comment by jinzhu** [comment]
Are you deploying a binary to server with bindatafs? https://github.com/qor/bindatafs
