### ISSUE TITLE
Full featured example app

### ISSUE THREAD

**Issue by alexmironof** [qor/qor-example#68]
It would be nice to see full featured example app.
With working orders, checkout, cart etc.
I think it is most important feature and it would attract more contributors to QOR SDK

**Comment by jinzhu** [comment]
@alexmironof thank you for your suggestion, our main focus is still extract common things from EC and config it into qor-example, hopefully we could have a more complete example app soon.

thank you ;)

**Comment by alexmironof** [comment]
@jinzhu Thanks for the response! we wil try to make some more PR's with common e-commerce functionality like:
- categories
- cart
- orders
- cash on delivery payment method
- fixed rate currier delivery method

**Comment by jinzhu** [comment]
cool, thank you!

let me know if I could help anything.

**Comment by alexmironof** [comment]
@jinzhu Thanks for you support! I'll publish some updates on categories tomorrow to [firestudios/qor-example](/firestudios/qor-example)
