### ISSUE TITLE
support persian language fa-IR

### ISSUE THREAD

**Issue by majidkarimizadeh** [qor/qor-example#70]
hi...
I trying to save persian text to db but i get this error...
`Error 1366: Incorrect string value: '\xD8\xB4\xD8\xB3\xDB\x8C...' for column 'name' at row 1`
can any one help me...?
tnx

**Comment by raven-chen** [comment]
Hi @majidkarimizadeh 

It looks like a encoding problem. Are you using UTF-8 in the database?

**Comment by majidkarimizadeh** [comment]
tnx...
it was foolish mistake
