### ISSUE TITLE
How to Integrate with angular2 or react.js

### ISSUE THREAD

**Issue by marcosguti** [qor/qor-example#74]
What is the best way to integrate this application with some javascript frontend framework like react or angular2, are there limitations to doing this?

**Comment by alexmironof** [comment]
I think there is no limitations there. You just need to create an API that mathes your needs and consume it with your favorite frontend framework.

Here simple example [qor-example#restful-api](https://github.com/qor/qor-example#restful-api) 
and it mounted here [main.go#L24](https://github.com/qor/qor-example/blob/master/main.go#L24)

Also check out [yoonic/nicistore](https://github.com/yoonic/nicistore) it is nice `react` storefront wich you can also use with `qor` if you write the right API :wink:

**Comment by marcosguti** [comment]
cors headers are default enabled in the QOR API? I had this error in browser when requesting the API 
`Fetch API cannot load https://demo.getqor.com/api/products.json. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.` How do you fix this on the server? Or can be solved from the frontend?

**Comment by jinzhu** [comment]
You should not rely qor demo's API to build any thing ;)

For your own API service, you could add this `'Access-Control-Allow-Origin'` header with your router's middleware
