### ISSUE TITLE
demo account doesnt work in localhost

### ISSUE THREAD

**Issue by medyagh** [qor/qor-example#80]
I cloned this repo and run it, but when I enter the demo user cred it wont login. (username dev@getqor.com and password testing) 
I get this message
```
invalid email and/or password
```
the demo user/pass works on the hosted demo on your website but not locally. why?

I tried to create a new user myself but I got into this other issue https://github.com/qor/qor-example/issues/79

**Comment by alexmironof** [comment]
You have an empty database.
run `go run db/seeds/main.go db/seeds/seeds.go`

**Comment by medyagh** [comment]
ah I can't belive I didnt do that. 

thanks that solved this issue.
