### ISSUE TITLE
(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)

### ISSUE THREAD

**Issue by daniel-007** [qor/qor-example#91]
请问这个错误是什么原因？(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)

**Comment by daniel-007** [comment]
$ go run main.go
Failed to create unique index for translations key & locale, got: Error 1170: BLOB/TEXT column 'key' used in key specification without a key length

(Error 1170: BLOB/TEXT column 'key' used in key specification without a key length)
[2017-06-05 09:20:06]
[auth]     Loading
[confirm]  Loading
[recover]  Loading
[register] Loading
[warning] duplicated callback `qor_admin:composite_primary_key` from D:/go_work/src/github.com/qor/admin/composite_primary_key_callback.go:31
[warning] duplicated callback `qor_admin:composite_primary_key` from D:/go_work/src/github.com/qor/admin/composite_primary_key_callback.go:32
[warning] duplicated callback `qor_admin:composite_primary_key` from D:/go_work/src/github.com/qor/admin/composite_primary_key_callback.go:32

(Error 1071: Specified key was too long; max key length is 3072 bytes)
[2017-06-05 09:20:18]
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> github.com/qor/qor-example/app/controllers.HomeIndex (4 handlers)
[GIN-debug] GET    /products/:code           --> github.com/qor/qor-example/app/controllers.ProductShow (4 handlers)
[GIN-debug] GET    /category/:code           --> github.com/qor/qor-example/app/controllers.CategoryShow (4 handlers)
[GIN-debug] GET    /switch_locale            --> github.com/qor/qor-example/app/controllers.SwitchLocale (4 handlers)
[recover]  Route: /auth/recover
[recover]  Route: /auth/recover/complete
[register] Route: /auth/register
[auth]     Route: /auth/login
[auth]     Route: /auth/logout
[confirm]  Route: /auth/confirm
Listening on: 7000

(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)
[2017-06-05 09:20:37]

(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)
[2017-06-05 09:20:37]

(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)
[2017-06-05 09:20:37]

(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)
[2017-06-05 09:20:37]
[GIN] 2017/06/05 - 09:20:37 | 200 |         347ms | ::1 |   GET     /

(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)
[2017-06-05 09:20:37]

(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)
[2017-06-05 09:20:37]

(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)
[2017-06-05 09:20:37]

(Error 1146: Table 'qor_example.qor_widget_settings' doesn't exist)
[2017-06-05 09:20:37]
[GIN] 2017/06/05 - 09:20:37 | 200 |          31ms | ::1 |   GET     /

**Comment by alexmironof** [comment]
try to run `go run db/seeds/main.go db/seeds/seeds.go`

**Comment by daniel-007** [comment]
@alexmironof 是表不存在，是初始化阶段没有创建这张表，还没到运行生成数据阶段。

**Comment by alexmironof** [comment]
I think you have outdated packages or you need to `db.DB.AutoMigrate`

**Comment by daniel-007** [comment]
谢谢，问题已经解决，是因为数据库编码导致的。

**Comment by alexmironof** [comment]
nice :+1:
