### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by a-jahanshahlo** [qor/qor-example#99]
Why this files aren't at the config path? 

`Failed to find configuration config/application.yml
Failed to find configuration config/smtp.yml, using example file config/smtp.example.yml
Failed to find configuration config/database.yml, using example file config/database.example.yml
panic: Error 1045: Access denied for user 'root'@'localhost' (using password: NO)`

**Comment by alexmironof** [comment]
`application.yml` is really missing, but is's not critical.
Also error message says that it using `*.example.yml` files, so you need to copy contents to `*.yml` files

**Comment by jinzhu** [comment]
Added the missing `application.example.yml` file, you need to create a copy of those files with your own setting.
